[2025-02-24T11:18:18.189+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:18:18.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:18:18.191+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:18:18.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:18:18.212+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:18:18.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:18:18.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:18:18.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.038 seconds
[2025-02-24T11:18:48.994+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:18:48.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:18:48.996+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:18:48.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:18:49.006+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:18:49.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:18:49.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:18:49.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.029 seconds
[2025-02-24T11:19:19.407+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:19:19.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:19:19.410+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:19:19.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:19:19.418+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:19:19.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:19:19.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:19:19.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T11:19:49.742+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:19:49.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:19:49.744+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:19:49.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:19:49.755+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:19:49.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:19:49.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:19:49.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.029 seconds
[2025-02-24T11:20:20.090+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:20:20.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:20:20.092+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:20:20.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:20:20.098+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:20:20.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:20:20.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:20:20.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.022 seconds
[2025-02-24T11:20:50.972+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:20:50.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:20:50.974+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:20:50.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:20:50.981+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:20:50.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:20:50.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:20:50.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:21:21.793+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:21:21.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:21:21.795+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:21:21.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:21:21.804+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:21:21.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:21:21.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:21:21.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T11:21:52.709+0000] {processor.py:186} INFO - Started process (PID=529) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:21:52.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:21:52.711+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:21:52.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:21:52.720+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:21:52.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:21:52.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:21:52.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:22:22.755+0000] {processor.py:186} INFO - Started process (PID=593) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:22:22.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:22:22.758+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:22:22.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:22:22.765+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:22:22.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:22:22.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:22:22.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:22:53.073+0000] {processor.py:186} INFO - Started process (PID=659) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:22:53.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:22:53.075+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:22:53.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:22:53.082+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:22:53.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:22:53.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:22:53.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:23:23.835+0000] {processor.py:186} INFO - Started process (PID=724) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:23:23.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:23:23.838+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:23:23.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:23:23.844+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:23:23.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:23:23.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:23:23.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:23:54.761+0000] {processor.py:186} INFO - Started process (PID=789) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:23:54.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:23:54.763+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:23:54.762+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:23:54.771+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:23:54.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:23:54.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:23:54.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:24:25.728+0000] {processor.py:186} INFO - Started process (PID=854) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:24:25.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:24:25.730+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:24:25.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:24:25.736+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:24:25.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:24:25.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:24:25.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:24:56.686+0000] {processor.py:186} INFO - Started process (PID=919) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:24:56.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:24:56.688+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:24:56.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:24:56.695+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:24:56.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:24:56.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:24:56.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T11:25:27.573+0000] {processor.py:186} INFO - Started process (PID=984) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:25:27.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:25:27.575+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:25:27.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:25:27.583+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:25:27.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:25:27.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:25:27.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:25:58.338+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:25:58.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:25:58.339+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:25:58.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:25:58.350+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:25:58.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:25:58.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:25:58.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:26:29.151+0000] {processor.py:186} INFO - Started process (PID=1114) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:26:29.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:26:29.153+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:26:29.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:26:29.160+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:26:29.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:26:29.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:26:29.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:27:00.058+0000] {processor.py:186} INFO - Started process (PID=1179) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:27:00.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:27:00.062+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:27:00.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:27:00.070+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:27:00.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:27:00.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:27:00.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:27:31.040+0000] {processor.py:186} INFO - Started process (PID=1244) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:27:31.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:27:31.042+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:27:31.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:27:31.049+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:27:31.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:27:31.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:27:31.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:28:01.872+0000] {processor.py:186} INFO - Started process (PID=1309) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:28:01.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:28:01.874+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:28:01.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:28:01.882+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:28:01.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:28:01.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:28:01.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:28:32.813+0000] {processor.py:186} INFO - Started process (PID=1374) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:28:32.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:28:32.815+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:28:32.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:28:32.826+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:28:32.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:28:32.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:28:32.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T11:29:03.811+0000] {processor.py:186} INFO - Started process (PID=1438) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:29:03.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:29:03.813+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:29:03.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:29:03.843+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:29:03.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:29:03.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:29:03.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2025-02-24T11:29:34.176+0000] {processor.py:186} INFO - Started process (PID=1503) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:29:34.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:29:34.178+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:29:34.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:29:34.184+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:29:34.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:29:34.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:29:34.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.022 seconds
[2025-02-24T11:30:04.973+0000] {processor.py:186} INFO - Started process (PID=1568) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:30:04.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:30:04.975+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:30:04.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:30:04.982+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:30:04.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:30:04.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:30:04.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:30:35.873+0000] {processor.py:186} INFO - Started process (PID=1633) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:30:35.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:30:35.876+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:30:35.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:30:35.890+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:30:35.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:30:35.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:30:35.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.035 seconds
[2025-02-24T11:31:06.752+0000] {processor.py:186} INFO - Started process (PID=1698) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:31:06.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:31:06.754+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:31:06.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:31:06.764+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:31:06.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:31:06.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:31:06.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:31:37.602+0000] {processor.py:186} INFO - Started process (PID=1763) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:31:37.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:31:37.605+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:31:37.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:31:37.613+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:31:37.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:31:37.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:31:37.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T11:32:08.481+0000] {processor.py:186} INFO - Started process (PID=1828) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:32:08.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:32:08.483+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:32:08.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:32:08.490+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:32:08.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:32:08.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:32:08.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:32:39.418+0000] {processor.py:186} INFO - Started process (PID=1893) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:32:39.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:32:39.421+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:32:39.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:32:39.431+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:32:39.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:32:39.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:32:39.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.030 seconds
[2025-02-24T11:33:10.294+0000] {processor.py:186} INFO - Started process (PID=1958) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:33:10.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:33:10.296+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:33:10.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:33:10.309+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:33:10.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:33:10.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:33:10.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.029 seconds
[2025-02-24T11:33:41.338+0000] {processor.py:186} INFO - Started process (PID=2023) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:33:41.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:33:41.340+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:33:41.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:33:41.350+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:33:41.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:33:41.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:33:41.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:34:11.892+0000] {processor.py:186} INFO - Started process (PID=2088) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:34:11.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:34:11.894+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:34:11.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:34:11.901+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:34:11.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:34:11.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:34:11.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:34:42.219+0000] {processor.py:186} INFO - Started process (PID=2153) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:34:42.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:34:42.221+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:34:42.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:34:42.228+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:34:42.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:34:42.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:34:42.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:35:13.179+0000] {processor.py:186} INFO - Started process (PID=2218) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:35:13.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:35:13.180+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:35:13.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:35:13.187+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:35:13.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:35:13.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:35:13.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:35:44.064+0000] {processor.py:186} INFO - Started process (PID=2283) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:35:44.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:35:44.066+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:35:44.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:35:44.073+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:35:44.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:35:44.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:35:44.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T11:36:15.005+0000] {processor.py:186} INFO - Started process (PID=2348) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:36:15.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:36:15.008+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:36:15.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:36:15.015+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:36:15.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:36:15.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:36:15.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T11:36:45.934+0000] {processor.py:186} INFO - Started process (PID=2413) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:36:45.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:36:45.936+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:36:45.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:36:45.943+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:36:45.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:36:45.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:36:45.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:37:16.887+0000] {processor.py:186} INFO - Started process (PID=2478) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:37:16.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:37:16.889+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:37:16.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:37:16.897+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:37:16.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:37:16.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:37:16.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:37:47.894+0000] {processor.py:186} INFO - Started process (PID=2543) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:37:47.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:37:47.896+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:37:47.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:37:47.903+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:37:47.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:37:47.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:37:47.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:38:18.859+0000] {processor.py:186} INFO - Started process (PID=2608) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:38:18.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:38:18.861+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:38:18.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:38:18.867+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:38:18.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:38:18.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:38:18.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:38:49.772+0000] {processor.py:186} INFO - Started process (PID=2673) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:38:49.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:38:49.774+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:38:49.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:38:49.782+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:38:49.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:38:49.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:38:49.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:39:20.619+0000] {processor.py:186} INFO - Started process (PID=2738) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:39:20.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:39:20.621+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:39:20.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:39:20.627+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:39:20.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:39:20.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:39:20.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:39:51.528+0000] {processor.py:186} INFO - Started process (PID=2802) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:39:51.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:39:51.530+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:39:51.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:39:51.538+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:39:51.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:39:51.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:39:51.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:40:21.622+0000] {processor.py:186} INFO - Started process (PID=2867) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:40:21.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:40:21.624+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:40:21.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:40:21.631+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:40:21.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:40:21.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:40:21.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:40:52.172+0000] {processor.py:186} INFO - Started process (PID=2932) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:40:52.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:40:52.174+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:40:52.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:40:52.185+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:40:52.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:40:52.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:40:52.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.032 seconds
[2025-02-24T11:41:22.517+0000] {processor.py:186} INFO - Started process (PID=3003) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:41:22.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:41:22.519+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:41:22.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:41:22.527+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:41:22.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:41:22.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:41:22.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:41:52.805+0000] {processor.py:186} INFO - Started process (PID=3068) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:41:52.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:41:52.807+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:41:52.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:41:52.813+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:41:52.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:41:52.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:41:52.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:42:22.989+0000] {processor.py:186} INFO - Started process (PID=3133) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:42:22.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:42:22.991+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:42:22.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:42:22.997+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:42:22.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:42:22.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:42:23.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.022 seconds
[2025-02-24T11:42:53.504+0000] {processor.py:186} INFO - Started process (PID=3198) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:42:53.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:42:53.506+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:42:53.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:42:53.513+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:42:53.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:42:53.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:42:53.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:43:23.886+0000] {processor.py:186} INFO - Started process (PID=3263) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:43:23.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:43:23.888+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:43:23.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:43:23.895+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:43:23.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:43:23.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:43:23.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:43:54.009+0000] {processor.py:186} INFO - Started process (PID=3328) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:43:54.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:43:54.011+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:43:54.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:43:54.018+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:43:54.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:43:54.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:43:54.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:44:24.269+0000] {processor.py:186} INFO - Started process (PID=3393) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:44:24.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:44:24.272+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:44:24.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:44:24.280+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:44:24.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:44:24.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:44:24.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T11:44:54.424+0000] {processor.py:186} INFO - Started process (PID=3458) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:44:54.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:44:54.427+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:44:54.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:44:54.436+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:44:54.434+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:44:54.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:44:54.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:45:24.627+0000] {processor.py:186} INFO - Started process (PID=3523) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:45:24.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:45:24.628+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:45:24.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:45:24.639+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:45:24.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:45:24.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:45:24.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T11:45:54.877+0000] {processor.py:186} INFO - Started process (PID=3588) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:45:54.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:45:54.879+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:45:54.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:45:54.888+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:45:54.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:45:54.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:45:54.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:46:25.004+0000] {processor.py:186} INFO - Started process (PID=3653) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:46:25.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:46:25.006+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:46:25.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:46:25.014+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:46:25.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:46:25.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:46:25.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:46:55.285+0000] {processor.py:186} INFO - Started process (PID=3718) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:46:55.286+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:46:55.287+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:46:55.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:46:55.293+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:46:55.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:46:55.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:46:55.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:47:25.399+0000] {processor.py:186} INFO - Started process (PID=3783) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:47:25.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:47:25.401+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:47:25.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:47:25.408+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:47:25.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:47:25.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:47:25.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:47:55.675+0000] {processor.py:186} INFO - Started process (PID=3849) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:47:55.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:47:55.677+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:47:55.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:47:55.684+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:47:55.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:47:55.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:47:55.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:48:26.459+0000] {processor.py:186} INFO - Started process (PID=3914) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:48:26.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:48:26.461+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:48:26.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:48:26.470+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:48:26.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:48:26.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:48:26.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:48:57.429+0000] {processor.py:186} INFO - Started process (PID=3979) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:48:57.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:48:57.432+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:48:57.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:48:57.456+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:48:57.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:48:57.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:48:57.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.044 seconds
[2025-02-24T11:49:28.088+0000] {processor.py:186} INFO - Started process (PID=4044) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:49:28.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:49:28.091+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:49:28.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:49:28.100+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:49:28.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:49:28.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:49:28.114+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.030 seconds
[2025-02-24T11:49:58.693+0000] {processor.py:186} INFO - Started process (PID=4109) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:49:58.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:49:58.695+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:49:58.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:49:58.701+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:49:58.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:49:58.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:49:58.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.022 seconds
[2025-02-24T11:50:29.146+0000] {processor.py:186} INFO - Started process (PID=4174) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:50:29.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:50:29.148+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:50:29.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:50:29.157+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:50:29.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:50:29.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:50:29.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T11:50:59.423+0000] {processor.py:186} INFO - Started process (PID=4239) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:50:59.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:50:59.425+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:50:59.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:50:59.434+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:50:59.432+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:50:59.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:50:59.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:51:30.327+0000] {processor.py:186} INFO - Started process (PID=4304) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:51:30.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:51:30.329+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:51:30.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:51:30.335+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:51:30.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:51:30.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:51:30.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T11:52:00.379+0000] {processor.py:186} INFO - Started process (PID=4368) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:52:00.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:52:00.381+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:52:00.381+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:52:00.388+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:52:00.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:52:00.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:52:00.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T11:52:31.108+0000] {processor.py:186} INFO - Started process (PID=4434) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:52:31.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:52:31.110+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:52:31.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:52:31.116+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:52:31.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:52:31.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:52:31.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.022 seconds
[2025-02-24T11:53:01.799+0000] {processor.py:186} INFO - Started process (PID=4499) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:53:01.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:53:01.804+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:53:01.804+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:53:01.812+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:53:01.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:53:01.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:53:01.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T11:53:32.756+0000] {processor.py:186} INFO - Started process (PID=4565) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:53:32.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:53:32.758+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:53:32.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:53:32.766+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:53:32.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:53:32.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:53:32.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:54:03.791+0000] {processor.py:186} INFO - Started process (PID=4630) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:54:03.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:54:03.793+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:54:03.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:54:03.801+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:54:03.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:54:03.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:54:03.812+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:54:34.375+0000] {processor.py:186} INFO - Started process (PID=4695) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:54:34.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:54:34.377+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:54:34.377+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:54:34.385+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:54:34.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:54:34.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:54:34.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:55:04.997+0000] {processor.py:186} INFO - Started process (PID=4760) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:55:04.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:55:04.999+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:55:04.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:55:05.007+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:55:05.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:55:05.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:55:05.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:55:36.010+0000] {processor.py:186} INFO - Started process (PID=4825) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:55:36.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:55:36.012+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:55:36.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:55:36.020+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:55:36.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:55:36.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:55:36.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T11:56:06.943+0000] {processor.py:186} INFO - Started process (PID=4890) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:56:06.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:56:06.950+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:56:06.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:56:06.958+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:56:06.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:56:06.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:56:06.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.031 seconds
[2025-02-24T11:56:37.068+0000] {processor.py:186} INFO - Started process (PID=4955) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:56:37.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:56:37.070+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:56:37.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:56:37.080+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:56:37.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:56:37.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:56:37.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T11:57:07.926+0000] {processor.py:186} INFO - Started process (PID=5020) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:57:07.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:57:07.928+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:57:07.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:57:07.936+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:57:07.933+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:57:07.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:57:07.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T11:57:37.993+0000] {processor.py:186} INFO - Started process (PID=5084) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:57:37.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:57:37.996+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:57:37.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:57:38.004+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:57:38.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:57:38.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:57:38.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T11:58:08.171+0000] {processor.py:186} INFO - Started process (PID=5150) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:58:08.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:58:08.175+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:58:08.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:58:08.191+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:58:08.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:58:08.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:58:08.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.036 seconds
[2025-02-24T11:58:38.553+0000] {processor.py:186} INFO - Started process (PID=5215) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:58:38.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:58:38.555+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:58:38.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:58:38.562+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:58:38.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:58:38.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:58:38.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T11:59:09.483+0000] {processor.py:186} INFO - Started process (PID=5280) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:59:09.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:59:09.485+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:59:09.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:59:09.497+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:59:09.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:59:09.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:59:09.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.029 seconds
[2025-02-24T11:59:40.337+0000] {processor.py:186} INFO - Started process (PID=5345) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:59:40.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T11:59:40.339+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:59:40.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:59:40.344+0000] {logging_mixin.py:190} INFO - [2025-02-24T11:59:40.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T11:59:40.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T11:59:40.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T12:00:11.120+0000] {processor.py:186} INFO - Started process (PID=5410) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:00:11.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:00:11.123+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:00:11.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:00:11.133+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:00:11.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:00:11.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:00:11.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.028 seconds
[2025-02-24T12:00:41.999+0000] {processor.py:186} INFO - Started process (PID=5475) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:00:42.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:00:42.001+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:00:42.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:00:42.009+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:00:42.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:00:42.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:00:42.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T12:01:12.723+0000] {processor.py:186} INFO - Started process (PID=5540) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:01:12.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:01:12.726+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:01:12.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:01:12.732+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:01:12.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:01:12.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:01:12.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T12:01:42.883+0000] {processor.py:186} INFO - Started process (PID=5605) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:01:42.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:01:42.885+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:01:42.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:01:42.893+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:01:42.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:01:42.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:01:42.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T12:02:13.065+0000] {processor.py:186} INFO - Started process (PID=5670) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:02:13.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:02:13.067+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:02:13.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:02:13.074+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:02:13.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:02:13.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:02:13.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T12:02:43.383+0000] {processor.py:186} INFO - Started process (PID=5735) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:02:43.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:02:43.385+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:02:43.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:02:43.392+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:02:43.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:02:43.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:02:43.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.026 seconds
[2025-02-24T12:03:14.031+0000] {processor.py:186} INFO - Started process (PID=5800) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:03:14.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:03:14.033+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:03:14.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:03:14.040+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:03:14.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:03:14.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:03:14.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.030 seconds
[2025-02-24T12:03:44.306+0000] {processor.py:186} INFO - Started process (PID=5865) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:03:44.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:03:44.309+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:03:44.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:03:44.316+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:03:44.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:03:44.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:03:44.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
[2025-02-24T12:04:15.175+0000] {processor.py:186} INFO - Started process (PID=5930) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:04:15.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:04:15.177+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:04:15.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:04:15.185+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:04:15.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:04:15.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:04:15.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T12:04:46.145+0000] {processor.py:186} INFO - Started process (PID=5995) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:04:46.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:04:46.148+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:04:46.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:04:46.157+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:04:46.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:04:46.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:04:46.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.030 seconds
[2025-02-24T12:05:16.259+0000] {processor.py:186} INFO - Started process (PID=6060) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:05:16.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:05:16.261+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:05:16.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:05:16.272+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:05:16.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:05:16.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:05:16.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.029 seconds
[2025-02-24T12:05:46.360+0000] {processor.py:186} INFO - Started process (PID=6125) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:05:46.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:05:46.363+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:05:46.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:05:46.370+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:05:46.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:05:46.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:05:46.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T12:06:16.607+0000] {processor.py:186} INFO - Started process (PID=6190) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:06:16.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:06:16.615+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:06:16.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:06:16.622+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:06:16.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:06:16.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:06:16.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.031 seconds
[2025-02-24T12:06:46.943+0000] {processor.py:186} INFO - Started process (PID=6255) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:06:46.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:06:46.945+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:06:46.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:06:46.952+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:06:46.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:06:46.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:06:46.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.024 seconds
[2025-02-24T12:07:18.186+0000] {processor.py:186} INFO - Started process (PID=6317) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:07:18.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:07:18.188+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:07:18.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:07:18.195+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:07:18.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:07:18.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:07:18.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.025 seconds
[2025-02-24T12:07:48.542+0000] {processor.py:186} INFO - Started process (PID=6369) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:07:48.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:07:48.544+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:07:48.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:07:48.550+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:07:48.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:07:48.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:07:48.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.023 seconds
[2025-02-24T12:08:19.772+0000] {processor.py:186} INFO - Started process (PID=6432) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:08:19.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-24T12:08:19.774+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:08:19.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:08:19.783+0000] {logging_mixin.py:190} INFO - [2025-02-24T12:08:19.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 2, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.kubernetes_pod'
[2025-02-24T12:08:19.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-24T12:08:19.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.027 seconds
